title: [Network+ N10-008 Study Journal]
description: [I hope you enjoy my collection of study materials for the CompTIA Network+ N10-008 exam!]

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

defaults:
  - scope:
      path: "/"
    values:
      layout: default
  - scope:
      path: "_posts"
    values:
      layout: post

permalink: /:year/:month/:day/:title/
